owner: bilbilak
repo: status

workflowSchedule:
  uptime: "*/15 * * * *"

status-website:
  cname: bilbilak.dev
  baseUrl: /status
  name: Bilbilak Services Status
  logoUrl: https://raw.githubusercontent.com/bilbilak/.github/main/.github/assets/bilbilak-logo.png
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER
  metaTags:
    - name: "robots"
      content: "noindex"
  robotsText: |
    User-agent: *
    Disallow: /

i18n:
  footer: ''

sites:
